"""empty message

Revision ID: 301f6048fcf3
Revises: 
Create Date: 2024-09-20 16:07:56.405237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301f6048fcf3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('ingreso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarjeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('banco', sa.String(length=100), nullable=False),
    sa.Column('es_adicional', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gasto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('informacion_adicional', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gasto_tarjeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('concepto', sa.String(length=100), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('cuota', sa.String(length=5), nullable=True),
    sa.Column('tarjeta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tarjeta_id'], ['tarjeta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gasto_tarjeta')
    op.drop_table('gasto')
    op.drop_table('tarjeta')
    op.drop_table('ingreso')
    op.drop_table('categoria')
    # ### end Alembic commands ###
